# If the variable ADELFA is not defined, set it to the default value 'adelfa'.
# To define this variable, run 'export ADELFA=<path_to_adelfa>' in your shell

ifndef ADELFA
ADELFA = adelfa
endif

all :
        $(MAKE) -C First\ Order

.PHONY : clean
clean :
        $(MAKE) -C First\ Order -k clean


